import random
import time
quotes = [
    "1. 'Be yourself; everyone else is already taken.' – Oscar Wilde",
    "2. 'Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.' – Albert Einstein",
    "3. 'So many books, so little time.' – Frank Zappa",
    "4. 'A room without books is like a body without a soul.' – Marcus Tullius Cicero",
    "5. 'Be the change that you wish to see in the world.' – Mahatma Gandhi",
    "6. 'If you tell the truth, you don't have to remember anything.' – Mark Twain",
    "7. 'A friend is someone who knows all about you and still loves you.' – Elbert Hubbard",
    "8. 'Always forgive your enemies; nothing annoys them so much.' – Oscar Wilde",
    "9. 'To live is the rarest thing in the world. Most people exist, that is all.' – Oscar Wilde",
    "10. 'Live as if you were to die tomorrow. Learn as if you were to live forever.' – Mahatma Gandhi",
    "11. 'Without music, life would be a mistake.' – Friedrich Nietzsche",
    "12. 'We accept the love we think we deserve.' – Stephen Chbosky",
    "13. 'It is better to be hated for what you are than to be loved for what you are not.' – André Gide",
    "14. 'Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.' – Marilyn Monroe",
    "15. 'Life is what happens to us while we are making other plans.' – Allen Saunders",
    "16. 'In three words I can sum up everything I've learned about life: it goes on.' – Robert Frost",
    "17. 'Don’t walk in front of me… I may not follow. Don’t walk behind me… I may not lead. Walk beside me… just be my friend.' – Albert Camus",
    "18. 'No one can make you feel inferior without your consent.' – Eleanor Roosevelt",
    "19. 'If you can't explain it to a six-year-old, you don't understand it yourself.' – Albert Einstein",
    "20. 'Everything you can imagine is real.' – Pablo Picasso",
    "21. 'Do what you can, with what you have, where you are.' – Theodore Roosevelt",
    "22. 'Success is not final, failure is not fatal: It is the courage to continue that counts.' – Winston Churchill",
    "23. 'You only live once, but if you do it right, once is enough.' – Mae West",
    "24. 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.' – Ralph Waldo Emerson",
    "25. 'Happiness is not something ready made. It comes from your own actions.' – Dalai Lama XIV",
    "26. 'Peace begins with a smile.' – Mother Teresa",
    "27. 'Turn your wounds into wisdom.' – Oprah Winfrey",
    "28. 'The only way to do great work is to love what you do.' – Steve Jobs",
    "29. 'The purpose of our lives is to be happy.' – Dalai Lama",
    "30. 'Do not go where the path may lead, go instead where there is no path and leave a trail.' – Ralph Waldo Emerson",
    "31. 'What lies behind us and what lies before us are tiny matters compared to what lies within us.' – Ralph Waldo Emerson",
    "32. 'Not all those who wander are lost.' – J.R.R. Tolkien",
    "33. 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.' – Aristotle",
    "34. 'It does not matter how slowly you go as long as you do not stop.' – Confucius",
    "35. 'The best way to predict your future is to create it.' – Abraham Lincoln",
    "36. 'Your time is limited, so don’t waste it living someone else’s life.' – Steve Jobs",
    "37. 'Believe you can and you're halfway there.' – Theodore Roosevelt",
    "38. 'Do not let making a living prevent you from making a life.' – John Wooden",
    "39. 'I have not failed. I've just found 10,000 ways that won't work.' – Thomas Edison",
    "40. 'Dream big and dare to fail.' – Norman Vaughan",
    "41. 'It is never too late to be what you might have been.' – George Eliot",
    "42. 'If you want to lift yourself up, lift up someone else.' – Booker T. Washington",
    "43. 'Try not to become a man of success. Rather become a man of value.' – Albert Einstein",
    "44. 'What you get by achieving your goals is not as important as what you become by achieving your goals.' – Zig Ziglar",
    "45. 'The journey of a thousand miles begins with one step.' – Lao Tzu",
    "46. 'Injustice anywhere is a threat to justice everywhere.' – Martin Luther King Jr.",
    "47. 'Education is the most powerful weapon which you can use to change the world.' – Nelson Mandela",
    "48. 'It always seems impossible until it's done.' – Nelson Mandela",
    "49. 'Strive not to be a success, but rather to be of value.' – Albert Einstein",
    "50. 'Everything has beauty, but not everyone sees it.' – Confucius",
    "51. 'Do one thing every day that scares you.' – Eleanor Roosevelt",
    "52. 'Success usually comes to those who are too busy to be looking for it.' – Henry David Thoreau",
    "53. 'Keep your face always toward the sunshine—and shadows will fall behind you.' – Walt Whitman",
    "54. 'It’s not whether you get knocked down, it’s whether you get up.' – Vince Lombardi",
    "55. 'Life isn’t about finding yourself. Life is about creating yourself.' – George Bernard Shaw",
    "56. 'Knowing yourself is the beginning of all wisdom.' – Aristotle",
    "57. 'The best revenge is massive success.' – Frank Sinatra",
    "58. 'Act as if what you do makes a difference. It does.' – William James",
    "59. 'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.' – Buddha",
    "60. 'What we think, we become.' – Buddha",
    "61. 'An unexamined life is not worth living.' – Socrates",
    "62. 'Turn your face to the sun and the shadows fall behind you.' – Maori Proverb",
    "63. 'Don't judge each day by the harvest you reap but by the seeds that you plant.' – Robert Louis Stevenson",
    "64. 'The only limit to our realization of tomorrow is our doubts of today.' – Franklin D. Roosevelt",
    "65. 'The mind is everything. What you think you become.' – Buddha",
    "66. 'Do what you feel in your heart to be right – for you’ll be criticized anyway.' – Eleanor Roosevelt",
    "67. 'Limit your ‘always’ and your ‘nevers’.' – Amy Poehler",
    "68. 'Nothing will work unless you do.' – Maya Angelou",
    "69. 'Success is getting what you want. Happiness is wanting what you get.' – W. P. Kinsella",
    "70. 'The secret of getting ahead is getting started.' – Mark Twain",
    "71. 'I would rather die of passion than of boredom.' – Vincent van Gogh",
    "72. 'Try to be a rainbow in someone’s cloud.' – Maya Angelou",
    "73. 'Stay hungry. Stay foolish.' – Steve Jobs",
    "74. 'A wise man can learn more from a foolish question than a fool can learn from a wise answer.' – Bruce Lee",
    "75. 'Logic will get you from A to B. Imagination will take you everywhere.' – Albert Einstein",
    "76. 'Our lives begin to end the day we become silent about things that matter.' – Martin Luther King Jr.",
    "77. 'We don’t see things as they are, we see them as we are.' – Anaïs Nin",
    "78. 'Mistakes are proof that you are trying.' – Jennifer Lim",
    "79. 'The greatest glory in living lies not in never falling, but in rising every time we fall.' – Nelson Mandela",
    "80. 'Sometimes the heart sees what is invisible to the eye.' – H. Jackson Brown Jr.",
    "81. 'Life is short, and it is up to you to make it sweet.' – Sarah Louise Delany",
    "82. 'The most courageous act is still to think for yourself. Aloud.' – Coco Chanel",
    "83. 'If opportunity doesn’t knock, build a door.' – Milton Berle",
    "84. 'I alone cannot change the world, but I can cast a stone across the waters to create many ripples.' – Mother Teresa",
    "85. 'You can’t go back and change the beginning, but you can start where you are and change the ending.' – C.S. Lewis",
    "86. 'Success is how high you bounce when you hit bottom.' – George S. Patton",
    "87. 'Only in the darkness can you see the stars.' – Martin Luther King Jr.",
    "88. 'A person who never made a mistake never tried anything new.' – Albert Einstein",
    "89. 'There is no greater agony than bearing an untold story inside you.' – Maya Angelou",
    "90. 'It is our choices that show what we truly are, far more than our abilities.' – J.K. Rowling",
    "91. 'Shoot for the moon. Even if you miss, you’ll land among the stars.' – Norman Vincent Peale",
    "92. 'Don’t count the days, make the days count.' – Muhammad Ali",
    "93. 'What you do makes a difference, and you have to decide what kind of difference you want to make.' – Jane Goodall",
    "94. 'The best way out is always through.' – Robert Frost",
    "95. 'In the middle of every difficulty lies opportunity.' – Albert Einstein",
    "96. 'To love and be loved is to feel the sun from both sides.' – David Viscott",
    "97. 'When you cease to dream, you cease to live.' – Malcolm Forbes",
    "98. 'Only those who dare to fail greatly can ever achieve greatly.' – Robert F. Kennedy",
    "99. 'A ship is safe in harbor, but that’s not what ships are for.' – William G.T. Shedd",
    "100. 'Don’t wait. The time will never be just right.' – Napoleon Hill"
]
a = random.choices(quotes)
count = 1
while(count<10):
 time.sleep(5)
 print(count,a)
 a = random.choices(quotes)
 count += 1